name: Using Defaults
on:
  push:
    branches: feature/defaults
jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src
    steps:
      - name: Create Source Directory
        run: mkdir src
        working-directory: .
      - name: Use Python
        run: print("I'm running python! Hissssss!")
        shell: python
      - name: Use Bash
        run: echo "I'm running hum-drum bash. Booo."
      - name: Use Bash Also
        run: echo "I'm running bash also. Booo."
  second-job:
    name: Second Job
    runs-on: ubuntu-latest
    steps:
      - name: Create Source Directory
        run: mkdir src
        shell: bash
        working-directory: .
      - name: Use Bash
        run: echo "I'm running bash. So sad."
        shell: bash
        working-directory: src